import React from 'react';
import {
  Box,
  Typography,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Divider,
  Button,
} from '@mui/material';
import { Download as DownloadIcon } from '@mui/icons-material';
import { api } from '../services/api';

export default function HowTalesWorks() {
  const handleDownload = async () => {
    try {
      const response = await api.get('/export/how-tales-works/word', {
        responseType: 'blob',
      });

      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'How_Tales_Works.docx');
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading document:', error);
      alert('Failed to download document. Please try again.');
    }
  };

  return (
    <Box sx={{ maxWidth: 1200, mx: 'auto' }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4" sx={{ fontWeight: 600, color: 'primary.main' }}>
          How Tales Works
        </Typography>
        <Button
          variant="contained"
          startIcon={<DownloadIcon />}
          onClick={handleDownload}
          sx={{
            backgroundColor: 'secondary.main',
            '&:hover': {
              backgroundColor: 'secondary.dark',
            }
          }}
        >
          Download as Word
        </Button>
      </Box>

      {/* Data Collection Methods */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h5" gutterBottom sx={{ fontWeight: 600, color: 'secondary.main' }}>
          Data Collection Methods
        </Typography>
        <Typography variant="body1" paragraph>
          The analysis of your brand's AI reputation is conducted using the Tales platform, which employs a systematic multi-platform AI querying methodology. Data is collected by submitting strategically designed queries to major large language models. These queries are automatically generated using AI to cover relevant topic areas including leadership and reputation, technology and innovation, and industry positioning.
        </Typography>
        <Typography variant="body1" paragraph>
          Critically, most queries are designed as "visibility tests" that deliberately exclude your brand name, allowing the study to measure organic mentions—instances where AI platforms independently reference your organization when answering relevant questions. A list of descriptive words ideally included in AI responses to describe your brand are also automatically generated by AI, as well as a list of your competitors. The queries, descriptors and competitors are all reviewed by a human and edited to ensure they fit your brand's needs. All responses are collected via API with timestamps and platform metadata, enabling temporal and cross-platform comparative analysis.
        </Typography>
        <Typography variant="body1" sx={{ fontStyle: 'italic', color: 'text.secondary' }}>
          <strong>Note:</strong> While the Tales platform allows users to assign priority levels (High, Medium, Low) to queries and descriptors for organizational purposes, these priority designations do not impact the quantitative analysis or metric calculations in any way—all queries and descriptors are weighted equally in the analysis.
        </Typography>
      </Paper>

      {/* Analytical Framework */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h5" gutterBottom sx={{ fontWeight: 600, color: 'secondary.main' }}>
          Analytical Framework
        </Typography>
        <Typography variant="body1" paragraph>
          The collected responses undergo a two-stage analysis process combining structured data extraction with AI-powered insight generation. In the first stage, Gemini 2.5 Pro analyzes each response to extract structured data including mention type (direct, indirect, or absent), brand positioning (categorized as leader, featured, listed, or not mentioned), sentiment classification (very positive, positive, neutral, negative, or mixed), associated descriptors and adjectives, competitor mentions, and cited sources.
        </Typography>
        <Typography variant="body1" paragraph>
          This extraction process is context-aware, incorporating your brand's industry context, strategic messaging, target descriptors, and known competitors to ensure relevant and accurate classification. In the second stage, Gemini 2.5 Pro synthesizes these structured findings with real-time industry news and comprehensive brand context to generate strategic insights, explicitly connecting each finding to specific performance gaps and opportunities.
        </Typography>
      </Paper>

      {/* Key Performance Metrics */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h5" gutterBottom sx={{ fontWeight: 600, color: 'secondary.main' }}>
          Key Performance Metrics
        </Typography>
        <Typography variant="body1" paragraph>
          The study calculates multiple quantitative metrics to assess your brand's AI reputation:
        </Typography>
        <Box component="ul" sx={{ pl: 3, mb: 2 }}>
          <Typography component="li" variant="body1" paragraph>
            <strong>Mention Rate:</strong> Measures the percentage of responses where the brand is referenced when not explicitly included in the query, indicating organic visibility in AI responses.
          </Typography>
          <Typography component="li" variant="body1" paragraph>
            <strong>Sentiment Distribution:</strong> Tracks the breakdown of positive, neutral, and negative associations across all mentions.
          </Typography>
          <Typography component="li" variant="body1" paragraph>
            <strong>Brand Positioning:</strong> Analyzes where your brand appears in AI-generated lists and discussions, calculating an average positioning score and leadership visibility percentage.
          </Typography>
          <Typography component="li" variant="body1" paragraph>
            <strong>Descriptor Match Rate:</strong> Compares target descriptors that your brand aims to be associated with against descriptors actually used by AI platforms, identifying alignment gaps.
          </Typography>
          <Typography component="li" variant="body1" paragraph>
            <strong>Share of Voice:</strong> Quantifies your brand's mentions relative to total organization mentions across all responses, including competitors, with weighting based on positioning strength.
          </Typography>
        </Box>
        <Typography variant="body1">
          All metrics are segmented by platform to identify which AI systems perform better or worse for your brand.
        </Typography>
      </Paper>

      {/* Mathematical Formulas */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h5" gutterBottom sx={{ fontWeight: 600, color: 'secondary.main', mb: 3 }}>
          Mathematical Formulas for Metric Calculations
        </Typography>

        {/* Brand Mentions */}
        <Box sx={{ mb: 4 }}>
          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            Brand Mentions (Mention Rate)
          </Typography>
          <Typography variant="body1" paragraph>
            The mention rate quantifies how frequently your brand is referenced by AI platforms when the brand name is not explicitly included in the query, measuring organic visibility.
          </Typography>
          <Box sx={{ bgcolor: 'grey.50', p: 2, borderRadius: 1, mb: 2, fontFamily: 'monospace' }}>
            Mention Rate (%) = (Number of Mentions / Total Qualifying Responses) × 100
          </Box>
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Component</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Definition</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell>Numerator</TableCell>
                  <TableCell>Count of responses where brand_mentioned field equals 'Yes' OR 'Indirect'</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Denominator</TableCell>
                  <TableCell>Total count of all responses in the analysis period</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Critical Exclusion</TableCell>
                  <TableCell>Both numerator and denominator exclude responses from queries where brand_in_query = True</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Rationale</TableCell>
                  <TableCell>Excluding branded queries prevents inflated mention rates and isolates organic AI platform behavior</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
          <Typography variant="body2" sx={{ mt: 1, fontStyle: 'italic', color: 'text.secondary' }}>
            Example: If there were 85 total responses from non-branded queries, and your brand was mentioned (directly or indirectly) in 34 of them, the mention rate would be (34/85) × 100 = 40.0%
          </Typography>
        </Box>

        <Divider sx={{ my: 3 }} />

        {/* Positioning Score */}
        <Box sx={{ mb: 4 }}>
          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            Positioning Score
          </Typography>
          <Typography variant="body1" paragraph>
            The positioning metric evaluates where your brand appears in AI-generated responses, with higher scores indicating more prominent placement.
          </Typography>
          <Box sx={{ bgcolor: 'grey.50', p: 2, borderRadius: 1, mb: 2, fontFamily: 'monospace' }}>
            Average Positioning Score = (Sum of Individual Position Scores) / Total Responses
          </Box>
          <Typography variant="body2" gutterBottom sx={{ fontWeight: 600 }}>
            Position Scoring System:
          </Typography>
          <TableContainer sx={{ mb: 2 }}>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Position Category</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Point Value</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Definition</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell>Leader</TableCell>
                  <TableCell>4 points</TableCell>
                  <TableCell>Your brand is presented as the top choice or industry leader</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Featured</TableCell>
                  <TableCell>3 points</TableCell>
                  <TableCell>Your brand receives prominent attention in the response, either through detailed discussion or being highlighted as a top recommendation</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Listed</TableCell>
                  <TableCell>2 points</TableCell>
                  <TableCell>Your brand is mentioned in a list with competitors</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Not Mentioned</TableCell>
                  <TableCell>1 point</TableCell>
                  <TableCell>Your brand was not mentioned in the response</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
          <Typography variant="body2" paragraph>
            Each response receives a score (1-4) based on how your brand was positioned. The scores are summed across all qualifying responses and divided by total response count to produce an average (range: 1.0 to 4.0). Responses from queries where brand_in_query = True are excluded.
          </Typography>
          <Box sx={{ bgcolor: 'grey.50', p: 2, borderRadius: 1, mt: 2, fontFamily: 'monospace' }}>
            Leadership Visibility (%) = ((Leader Count + Featured Count) / Total Responses) × 100
          </Box>
          <Typography variant="body2" paragraph sx={{ mt: 2, color: 'text.secondary' }}>
            Leadership Visibility is calculated by counting responses where your brand achieved either Leader or Featured positioning (the top two tiers), divided by total responses, excluding queries where your brand name was explicitly mentioned. This metric measures high-quality visibility—how often AI platforms actively recommend or prominently feature your brand, not just mention it. Unlike basic mention rate which only measures presence, Leadership Visibility captures strategic positioning strength. All responses (including those where your brand was not mentioned) are counted in the denominator, making this a strict measure of premium positioning.
          </Typography>
          <Typography variant="body2" sx={{ fontStyle: 'italic', color: 'text.secondary' }}>
            <strong>Example:</strong> If you have 85 total responses from non-branded queries, with 8 Leader positions and 16 Featured positions, your Leadership Visibility would be (8 + 16) / 85 × 100 = 28.2%. This means that in approximately 28% of AI responses, your brand receives top-tier positioning as a market leader or featured solution.
          </Typography>
        </Box>

        <Divider sx={{ my: 3 }} />

        {/* Share of Voice */}
        <Box sx={{ mb: 4 }}>
          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            Share of Voice
          </Typography>
          <Typography variant="body1" paragraph>
            Share of Voice quantifies your brand's relative visibility compared to all organizations (including competitors) mentioned across AI responses.
          </Typography>
          <Box sx={{ bgcolor: 'grey.50', p: 2, borderRadius: 1, mb: 2, fontFamily: 'monospace' }}>
            Share of Voice (%) = (Brand Mentions / Total All Organization Mentions) × 100
          </Box>
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Component</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Definition</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell>Brand Mentions (Numerator)</TableCell>
                  <TableCell>Count of responses where your brand achieved positioning of 'Leader', 'Featured', or 'Listed'</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Total Mentions (Denominator)</TableCell>
                  <TableCell>Sum of all organization mentions including: (1) your brand mentions and (2) all competitor mentions</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Competitor Counting</TableCell>
                  <TableCell>The competitors field contains comma-separated organization names; each occurrence increments that competitor's mention count</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Exclusion</TableCell>
                  <TableCell>Only responses from queries where brand_in_query = False are included</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
          <Typography variant="body2" sx={{ mt: 1, fontStyle: 'italic', color: 'text.secondary' }}>
            Example: If your brand appeared in 34 responses with qualifying positioning, and competitors appeared in a combined 56 responses, the total mentions would be 90. Your share of voice would be (34/90) × 100 = 37.8%
          </Typography>
        </Box>

        <Divider sx={{ my: 3 }} />

        {/* Target Descriptor Adoption */}
        <Box sx={{ mb: 4 }}>
          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            Target Descriptor Adoption
          </Typography>
          <Typography variant="body1" paragraph>
            Target descriptor adoption measures how successfully your brand has become associated with the specific descriptors and attributes it aims to own strategically.
          </Typography>
          <Box sx={{ bgcolor: 'grey.50', p: 2, borderRadius: 1, mb: 2, fontFamily: 'monospace' }}>
            Descriptor Match Rate (%) = (Number of Target Descriptors Found / Total Target Descriptors) × 100
          </Box>
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Component</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Definition</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell>Total Target Descriptors</TableCell>
                  <TableCell>Count of all descriptors configured as strategic targets for your brand in the platform</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Target Descriptors Found</TableCell>
                  <TableCell>Count of unique target descriptors that appear in at least one AI response</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Matching Logic</TableCell>
                  <TableCell>Case-insensitive matching; a target descriptor is counted as "found" if it appears in any response where your brand was mentioned</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Inclusion</TableCell>
                  <TableCell>This calculation INCLUDES responses from queries where brand_in_query = True (quality of associations matters regardless of query type)</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
          <Typography variant="body2" sx={{ mt: 1, fontStyle: 'italic', color: 'text.secondary' }}>
            Example: If your brand has 20 target descriptors and 13 of those descriptors appeared in at least one response, the descriptor match rate would be (13/20) × 100 = 65.0%
          </Typography>
        </Box>

        <Divider sx={{ my: 3 }} />

        {/* Competitive Threat Analysis */}
        <Box sx={{ mb: 4 }}>
          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            Competitive Threat Analysis
          </Typography>
          <Typography variant="body1" paragraph>
            Competitive threat analysis combines quantitative scoring with AI-powered qualitative analysis to identify and explain strategic competitive risks.
          </Typography>
          <Box sx={{ bgcolor: 'grey.50', p: 2, borderRadius: 1, mb: 2, fontFamily: 'monospace' }}>
            Threat Score = (mention_count × 0.7) + (negative_overlap × 2.0) + (positive_competitor × 1.5)
          </Box>
          <TableContainer sx={{ mb: 2 }}>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Component</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Weight</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Definition</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell>Mention Count</TableCell>
                  <TableCell>0.7</TableCell>
                  <TableCell>Total number of times the competitor is mentioned across all AI responses</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Negative Overlap</TableCell>
                  <TableCell>2.0</TableCell>
                  <TableCell>Count of responses where the competitor is mentioned AND your brand receives negative/very negative sentiment (indicates direct competitive pressure)</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Positive for Competitor</TableCell>
                  <TableCell>1.5</TableCell>
                  <TableCell>Count of responses where the competitor receives positive/very positive sentiment (indicates competitive advantage)</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
          <Typography variant="body2" paragraph sx={{ fontWeight: 600 }}>
            Threat Level Thresholds:
          </Typography>
          <Box component="ul" sx={{ pl: 3, mb: 2 }}>
            <Typography component="li" variant="body2">
              <strong>High Threat (score &gt; 50):</strong> Requires immediate strategic attention
            </Typography>
            <Typography component="li" variant="body2">
              <strong>Medium Threat (score 20-50):</strong> Requires monitoring
            </Typography>
            <Typography component="li" variant="body2">
              <strong>Low Threat (score &lt; 20):</strong> Minimal competitive pressure
            </Typography>
          </Box>
          <Typography variant="body2" gutterBottom sx={{ fontWeight: 600 }}>
            Report Generation Process:
          </Typography>
          <Box component="ol" sx={{ pl: 3 }}>
            <Typography component="li" variant="body2" paragraph>
              <strong>Quantitative Ranking:</strong> All competitors are scored using the threat formula above, and the top 3 threats are identified based on their scores.
            </Typography>
            <Typography component="li" variant="body2" paragraph>
              <strong>Data Collection:</strong> For the top 3 threats, the system gathers Share of Voice data, identifies specific query-response pairs where your brand was not mentioned but competitors were, and extracts "competitive loss" examples where both were mentioned but the competitor was positioned better.
            </Typography>
            <Typography component="li" variant="body2" paragraph>
              <strong>AI Analysis:</strong> Concrete response examples and competitive data for the top 3 threats are submitted to Gemini 2.5 Pro, which generates qualitative narrative analysis explaining why each competitor is a threat, what specific queries they are winning, what descriptors and positioning they have claimed, strategic implications, and recommended counter-actions.
            </Typography>
          </Box>
          <Typography variant="body2" sx={{ fontStyle: 'italic', color: 'text.secondary' }}>
            <strong>Rationale:</strong> The quantitative threat score efficiently identifies which competitors pose the greatest risk, while the AI-generated qualitative analysis provides strategic context and concrete examples that a formula alone cannot deliver.
          </Typography>
        </Box>

        {/* Summary Table */}
        <Box sx={{ mt: 4 }}>
          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            Summary of Metric Calculation Approaches
          </Typography>
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Metric</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Type</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Includes Branded Queries?</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Rationale</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell>Mention Rate</TableCell>
                  <TableCell>Quantitative Formula</TableCell>
                  <TableCell>No (Excluded)</TableCell>
                  <TableCell>Measures organic visibility without bias</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Positioning Score</TableCell>
                  <TableCell>Quantitative Formula</TableCell>
                  <TableCell>No (Excluded)</TableCell>
                  <TableCell>Assesses natural positioning</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Share of Voice</TableCell>
                  <TableCell>Quantitative Formula</TableCell>
                  <TableCell>No (Excluded)</TableCell>
                  <TableCell>Compares competitive visibility organically</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Descriptor Match</TableCell>
                  <TableCell>Quantitative Formula</TableCell>
                  <TableCell>Yes (Included)</TableCell>
                  <TableCell>Quality of associations matters regardless of query type</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Sentiment Distribution</TableCell>
                  <TableCell>Quantitative Formula</TableCell>
                  <TableCell>Yes (Included)</TableCell>
                  <TableCell>Sentiment reflects perception across all contexts</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Competitive Threats</TableCell>
                  <TableCell>Qualitative AI Analysis</TableCell>
                  <TableCell>Context-dependent</TableCell>
                  <TableCell>Strategic nuance requires pattern recognition</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
        </Box>
      </Paper>

      {/* Competitive Intelligence Analysis */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h5" gutterBottom sx={{ fontWeight: 600, color: 'secondary.main' }}>
          Competitive Intelligence Analysis
        </Typography>
        <Typography variant="body1" paragraph>
          Competitor analysis forms a critical component of the methodology, examining how your brand performs relative to other organizations in AI-generated discourse. The system tracks pre-configured competitors with metadata including organization type, focus areas, and key descriptors, while also automatically extracting mentions of organizations not initially identified as competitors.
        </Typography>
        <Typography variant="body1" paragraph>
          Co-occurrence analysis reveals which competitors frequently appear alongside your brand in AI responses, and comparative share of voice calculations quantify relative visibility. The analysis identifies specific queries where competitors received more favorable positioning than your brand, extracts the descriptors and positioning competitors own, and examines concrete response examples showing competitive advantages. These findings surface where the competitive gaps are and which strategic positioning is currently owned by rivals.
        </Typography>
      </Paper>

      {/* Working With the Findings */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h5" gutterBottom sx={{ fontWeight: 600, color: 'secondary.main' }}>
          Working With the Findings
        </Typography>
        <Typography variant="body1" paragraph>
          Tales reports describe what the data shows; they do not prescribe what to do about it. Reports and the accompanying spreadsheet exports are designed to be read directly, or handed to an AI assistant of your choosing along with whatever strategic context matters to your organization, so that any recommendations reflect priorities Tales has no visibility into.
        </Typography>
      </Paper>

      {/* Limitations */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h5" gutterBottom sx={{ fontWeight: 600, color: 'secondary.main' }}>
          Limitations and Considerations
        </Typography>
        <Typography variant="body1" paragraph>
          Several important limitations should be considered when interpreting these findings. AI platform responses can vary over time due to model updates, training data changes, and index refreshes, meaning that findings represent a snapshot rather than static characteristics. Finally, while the analysis identifies correlations between content strategies and AI reputation metrics, establishing direct causation requires controlled longitudinal studies that account for confounding variables such as broader industry trends, news coverage, and publication timing effects.
        </Typography>
      </Paper>
    </Box>
  );
}
